on:
  workflow_dispatch:

jobs:
  with-service:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - run: docker ps
      - name: Install pg_partman
        run: |
          sudo docker exec postgres git clone https://github.com/pgpartman/pg_partman.git
          sudo docker exec -w /pg_partman postgres make install
