on:
  workflow_dispatch:

jobs:
  with-service:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - name: Get Container Name
        run: |
          PG=$(docker ps --filter "name=postgres" --format "{{.Names}}")
          echo "PGNAME=$PG" >> "$GITHUB_ENV"
      - name: Install pg_partman
        run: |
          docker exec $PGNAME sudo apt -y install git-all make
          docker exec $PGNAME git clone https://github.com/pgpartman/pg_partman.git
          docker exec -w /pg_partman $PGNAME make install
